
    location /check-api/social-graph/get_followees {
      content_by_lua '
          local client = require "check-api/social-graph/get_followees"
          client.GetFollowees();
      ';
    }

    location /check-api/user-timeline/contains {
      content_by_lua '
          local client = require "check-api/user-timeline/contains"
          client.Contains();
      ';
    }

    location /check-api/home-timeline/contains {
      content_by_lua '
          local client = require "check-api/home-timeline/contains"
          client.Contains();
      ';
    }
